In [3]:
import numpy as np
from hmmlearn import hmm

In [4]:
# defining matrixes
np.random.seed(42)
componets = 6
delta = 0.05
m = 5
startprob = np.array([1, 0, 0, 0, 0, 0])
transtprob = np.array([[0.1, 0.9, 0, 0, 0, 0],
                        [0.2, 0, 0.1+delta, 0, 0, 0.7-delta],
                        [0, 0.5, 0, 0.5, 0, 0],
                        [0, 0, 0.5, 0.5, 0, 0],
                        [0, 0, 0.1, 0, 0.4, 0.5],
                        [0, 0.2, 0, 0, 0.7, 0.1]])
emissionprob = np.array([[0.25, 0.25, 0.25, 0.25],
                         [0.4, 0.3, 0.2, 0.1],
                         [0.4, 0.4, 0.1, 0.1],
                         [0.3, 0.3, 0.3, 0.1],
                         [0.2, 0.2, 0.2, 0.4],
                         [0.2, 0.2, 0.3, 0.3]
                         ])



In [5]:
model = hmm.CategoricalHMM(n_components=componets)
model.startprob_=startprob
model.transmat_ = transtprob
model.emissionprob_ = emissionprob

In [6]:
def observation_sample(model, k = 10):
    O,Q = model.sample(k*2)
    observations = O[np.arange(0,2*k,2)]
    return observations, Q

In [25]:
len(observation_sample(model)[0])

10

In [12]:
model.emissionprob_.shape[0]

6

In [13]:
np.zeros([6,0])

array([], shape=(6, 0), dtype=float64)

In [29]:
obs, real_states= observation_sample(model=model, k=200)

In [30]:
obs = obs.flatten()

In [31]:
obs

array([1, 1, 0, 2, 0, 1, 2, 3, 2, 0, 2, 0, 2, 2, 2, 2, 1, 0, 3, 0, 3, 2,
       1, 0, 3, 1, 0, 0, 1, 3, 3, 2, 1, 1, 1, 0, 3, 1, 2, 2, 0, 0, 0, 1,
       3, 2, 0, 3, 2, 0, 3, 3, 3, 1, 2, 3, 3, 1, 3, 3, 1, 0, 2, 1, 0, 1,
       3, 0, 3, 0, 3, 3, 1, 0, 3, 2, 3, 3, 0, 1, 3, 1, 0, 2, 0, 1, 3, 3,
       3, 2, 3, 3, 0, 2, 1, 3, 1, 0, 0, 3, 3, 3, 0, 3, 1, 2, 1, 3, 2, 1,
       3, 3, 3, 0, 0, 2, 0, 3, 3, 3, 1, 2, 2, 1, 0, 2, 1, 2, 1, 0, 0, 1,
       1, 3, 3, 3, 1, 0, 1, 0, 1, 1, 2, 0, 0, 0, 1, 0, 1, 0, 0, 2, 2, 2,
       0, 3, 0, 0, 2, 1, 1, 2, 0, 1, 1, 0, 3, 1, 1, 3, 0, 3, 0, 2, 3, 1,
       3, 2, 1, 2, 1, 1, 2, 1, 1, 1, 3, 3, 2, 2, 0, 3, 0, 3, 1, 0, 3, 1,
       0, 1], dtype=int64)

In [32]:
T = len(obs)*2

In [33]:
V = np.zeros((T,6))

In [142]:
V

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [34]:
for j in range(6):
    V[0][j] = startprob[j]*emissionprob[j][obs[0]]

In [35]:
for t in range(1,T):
    for j in range(6):
        if t%2 == 0:
            V[t][j] = max(V[t-1] * transtprob[:,j] * emissionprob[j][obs[int(t/2)]])
        else:
            V[t][j] = max(V[t-1] * transtprob[:,j])


In [154]:
V

array([[2.50000000e-01, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00],
       [2.50000000e-02, 2.25000000e-01, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00],
       [1.12500000e-02, 9.00000000e-03, 1.35000000e-02, 0.00000000e+00,
        0.00000000e+00, 2.92500000e-02],
       [1.80000000e-03, 1.01250000e-02, 1.35000000e-03, 6.75000000e-03,
        2.04750000e-02, 5.85000000e-03],
       [5.06250000e-04, 6.48000000e-04, 1.35000000e-03, 1.01250000e-03,
        1.63800000e-03, 2.04750000e-03],
       [1.29600000e-04, 6.75000000e-04, 5.06250000e-04, 6.75000000e-04,
        1.43325000e-03, 8.19000000e-04],
       [3.37500000e-05, 7.59375000e-05, 1.35000000e-04, 1.01250000e-04,
        1.14660000e-04, 1.43325000e-04],
       [1.51875000e-05, 6.75000000e-05, 5.06250000e-05, 6.75000000e-05,
        1.00327500e-04, 5.73300000e-05],
       [3.37500000e-06, 2.53125000e-06, 3.37500000e-06, 3.37500000e-06,
        1.60524000e-05, 

In [42]:
best_last_state = np.argmax(V[T-1])

In [43]:
best_path = [best_last_state]

In [124]:
max(np.array([1,2,3]) * np.array([1,2,3]) * 0.5)

4.5

In [38]:
t_prova = transtprob.copy()

In [39]:
t_prova[t_prova != 0] = 1

In [40]:
for i in range(T-2,-1,-1):
    best_last_state = np.argmax(V[i-1]*t_prova[:,best_last_state])
    best_path.append(best_last_state)

print(best_path)

[5, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 4, 4, 4, 4, 4, 5, 4, 5, 4, 5, 4, 4, 4, 4, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 4, 4, 4, 5, 4, 5, 4, 5, 4, 4, 4, 5, 4, 5, 4, 5, 4, 5, 4, 4, 4, 4, 4, 4, 4, 5, 1, 2, 3, 3, 2, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 4, 4, 4, 4, 4, 4, 5, 4, 5, 4, 5, 4, 5, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 4, 5, 4, 5, 1, 2, 1, 2, 4, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 4, 4, 4, 5, 1, 2, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 4, 5, 4, 5, 4, 5, 4, 5, 4, 4, 4, 4, 4, 5, 4, 5, 4, 5, 4, 5, 4, 4, 4, 4, 4, 4, 4, 5, 4, 4, 4, 4, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 4, 4, 4, 4, 5, 4, 5, 4, 5, 4, 4, 4, 5, 4, 5, 4, 5, 4, 4, 4, 4, 4, 4, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 4, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 4, 4, 5, 4, 5, 4, 5, 4, 4, 4, 4, 5, 4, 5, 4, 4, 4, 5, 4, 5, 4, 4, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 5, 4, 5, 4, 4, 4, 4, 4, 4, 4, 

In [44]:
for i in range(T-2,-1,-1):
    best_last_state = np.argmax(V[i-1]*transtprob[:,best_last_state])
    best_path.append(best_last_state)

print(best_path)

[5, 4, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 1, 2, 3, 2, 3, 2, 3, 3, 3, 2, 3, 2, 3, 3, 3, 2, 4, 5, 4, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 1, 2, 3, 3, 2, 3, 2, 3, 3, 3, 2, 3, 2, 3, 3, 3, 2, 3, 2, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 1, 2, 3, 2, 3, 2, 3, 2, 3, 2, 3, 2, 3, 2, 3, 2, 3, 3, 3, 2, 3, 2, 3, 2, 3, 2, 3, 2, 3, 2, 4, 4, 5, 4, 5, 4, 5, 1, 2, 3, 3, 2, 3, 2, 3, 2, 3, 3, 3, 2, 3, 3, 3, 2, 3, 2, 4, 5, 4, 5, 4, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 1, 2, 3, 2, 3, 2, 3, 2, 4, 5, 4, 5, 4, 5, 4, 5, 1, 2, 3, 2, 3, 2, 

In [19]:
np.flip(real_states)

array([3, 2, 3, 2, 4, 5, 4, 4, 4, 4, 5, 1, 0, 1, 0, 1, 0, 0, 1, 0])

In [46]:
sum(np.flip(best_path) == real_states)

117

In [82]:
def risk_check(path, m):
    path_np = np.array(path)
    path_np[path_np>=4] = 7
    for i in range(len(path) - m):
        if np.array_equal(path_np[i:i+m], np.array([7]*m)):
            # print("Fuori controllo")
            return True
    return False

In [83]:
risk_check(path=best_path, m=5)

True

In [73]:
path_np = np.array(best_path)

NameError: name 'path_np' is not defined

In [121]:
list(range(20,-1,-1))

[20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [95]:
max(transtprob[:,3]*V[0])

0.0

0